### PR TITLE
Update Rules.md

### PR DESCRIPTION
**Pull request by FifoF**
what do you think about this?

I don’t think it’s quite complete yet – I do think we should change a few things, so I’ve made a pull request before merging the changes.

### CODE REVIEW

**Comment by Aggy42** [comment]
While I do agree that it's not perfect yet, I think it looks pretty good so far.

**Comment by FifoF** [comment]
> While I do agree that it's not perfect yet, I think it looks pretty good so far.

You’re free to modify it – it won’t affect the master branch :)

**Comment by FifoF** [comment]
Anybody else? @nr0r?

**Comment by FifoF** [comment]
Come on! @Aggy42 @nr0r

**Comment by FifoF** [comment]
> I feel nothing else needs to be added at the moment.
Nice, thanks! We’ll wait for @nr0r’s feedback before we merge the changes.

**Comment by FifoF** [comment]
Well, she doesn’t seem to be active. What now?

**Comment by FifoF** [comment]
Thanks!

**Pull request merged**
